import extractor
import pytest


REFERENCE = 'ACGTCGATTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT'


TESTS = [
    # No variants
    (REFERENCE,
     REFERENCE,
     [{'location': {'start': {'position':  0, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
       'type': 'equal'}]),

    # Single variants

    ## Substitution: 7A>G
    (REFERENCE,
     'ACGTCGGTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 7, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 7, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  7, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Single nucleotide deletion: 7del
    (REFERENCE,
     'ACGTCGTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 7, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 6, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  7, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Multi nucleotide deletion: 7_8del
    (REFERENCE,
     'ACGTCGTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 8, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 6, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  8, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Single nucleotide insertion: 6_7insC
    (REFERENCE,
     'ACGTCGCATTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 7, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  6, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Multi nucleotide insertion: 6_7insCC
    (REFERENCE,
     'ACGTCGCCATTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 8, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  6, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Inversion: 7_11inv
    (REFERENCE,
     'ACGTCGCGAATCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 11, 'type': 'point'},
                    'type': 'range'},
        'type': 'inv'},
      {'location': {'start': {'position': 11, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Inversion: 6_7inv
    (REFERENCE,
     'ACGTCTCTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 5, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 5, 'type': 'point'},
                    'end':   {'position': 7, 'type': 'point'},
                    'type': 'range'},
        'type': 'inv'},
      {'location': {'start': {'position': 7, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Deletion/insertion 7delinsCC
    (REFERENCE,
     'ACGTCGCCTTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 7, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 8, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position':  7, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Deletion/insertion 21_23delinsTTTT
    (REFERENCE,
     'ACGTCGATTCGCTAGCTTCGTTTTGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 20, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 20, 'type': 'point'},
                    'end':   {'position': 23, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 20, 'type': 'point'},
                                     'end'  : {'position': 24, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position': 23, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

    ## Deletion/insertion 7_8delinsTC
    (REFERENCE,
     'ACGTCGTCTCGCTAGCTTCGGGGGATAGATAGAGATATAGAGAT',
     [{'location': {'start': {'position': 0, 'type': 'point'},
                    'end':   {'position': 6, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'},
      {'location': {'start': {'position': 6, 'type': 'point'},
                    'end':   {'position': 8, 'type': 'point'},
                    'type': 'range'},
        'insertions': [{'source': 'observed',
                        'location': {'start': {'position': 6, 'type': 'point'},
                                     'end'  : {'position': 8, 'type': 'point'},
                        'type': 'range'}}],
        'type': 'delins'},
      {'location': {'start': {'position': 8, 'type': 'point'},
                    'end':   {'position': 44, 'type': 'point'},
                    'type': 'range'},
        'type': 'equal'}]),

]


@pytest.mark.parametrize('reference, observed, variants', TESTS)
def test_variants(reference, observed, variants):
    assert variants == extractor.describe_dna(reference, observed)
